### ISSUE TITLE
Pre-compiled DLL's?

### ISSUE THREAD

**Issue by cmille34** [liubiaoyong/CrmSessionCookieRenamer#1]
I am not familiar with building projects like this, is the DLL that is compiled unique to my version of CRM or system? Can you simply post the actual files that need to go in the CRMWeb\bin folder?

**Comment by liubiaoyong** [comment]
I've upload a file named PreCompiled.zip. 
Just unzip the file, and copy the dll to the CRMWeb\bin. 
Don't override any file if exists.
[PreCompiled.zip](https://github.com/liubiaoyong/CrmSessionCookieRenamer/files/2965857/PreCompiled.zip)
